# this is the docker-compose version
version: '3.0'

# file version 2019-03-08-1616


networks:
    # network for this compose stack
    mbatchsa_network_<ENVIRON>:
        driver: bridge
        ipam:
            config:
            - subnet: <SUBNET>
services:
    mbatchsa_service:
        # use existing default network
        network_mode: bridge
        # restart this container if it crashes
        #restart: always
        build:
            # build from directory in context and Dockerfile
            context: .
            dockerfile: Dockerfile
        container_name: mbatchsa_cont_<ENVIRON>
        # update :latest to desired version
        image: <IMAGETXT>:<DESIREDTAG>
        volumes:
            # outside access for data files outside:inside
            - <MBATCH-DIR>:/MBATCH
            - <WEBSITE-DIR>:/WEBSITE
            # read-only file to set time and timezone to same in image as on server
            - /etc/localtime:/etc/localtime:ro
            - /etc/localtime:/etc/timezone:ro
        ports:
            # (outside)host port:container port(inside) for RStudio
            - "<OUTSIDE_PORT>:8787"
        tty: true
